export const matereal = [
  "Dəri",
  "Süni Dəri",
  "Qarışıq",
  "Parça",
  "Fiber (Lif)",
  "Mikrofiber (Lif)",
  "Toxunma",
  "Kətan",
  "Polyester",
  "Pambıq-Polyester",
  "Pambıq",
  "İpək",
  "Yun",
  "Şifon",
  "Denim",
  "Zərif Parça (Velvet)",
  "Elastik (Spandex)",
  "Atlas (Sətin)",
  "Fliş (Fleece)",
  "Dantel (Krujeva)",
  "Rayon",
  "Kaşmir",
  "Naylon",
  "Viskoz",
  "Akril",
  "Rezin",
  "Tor",
];

export const closureTypes = [
  "Qarmaq və Halqa",
  "Düymə",
  "Zəncirbənd",
  "Kəmər",
  "Sürüşdürərək geyinmə",
  "Yapışqan",
  "Bağcıq",
  "Keçirtməli bağlama",
  "Bağlamasız",
];

export const patterns = [
  "Tək rəng",
  "Cizgili",
  "Naxışlı",
  "Çap şəkilli",
  "Toxunma",
  "Rəngarəng",
  "Retro",
  "Zolaqlı",
  "Dama-dama",
  "Gül naxışlı",
  "Xallı",
  "Paisley (Şərq naxışı)",
  "Heyvan dərisi naxışı",
  "Həndəsi",
  "Kamuflyaj",
  "Abstrakt",
  "Əlişləməli",
];

export const glassType = ["Şüşə", "Plastik", "Şüşə/plastik", "Kristal"];
export const typeJewelry = [
  "Qolbağı",
  "Sırğa",
  "Boyunbağı",
  "Üzük",
  "Piercing",
  "Dəst 2li",
  "Dəst 3lü",
  "Dəst 4lü",
  "Digər",
];

export const typeBag = [
  "Bel çantası",
  "Çiyin çantası",
  "Məktəb çantası",
  "Əl çantası",
  "İdman çantası",
  "Səyahət çantası",
  "Çanta aksesuarları",
  "Digər",
];
