export const colors = [
  "Ağ",
  "Qara",
  "Qırmızı",
  "Yaşıl",
  "Göy",
  "Mavi",
  "Sarı",
  "Narıncı",
  "Bənövşəyi",
  "Çəhrayı",
  "Boz",
  "Qəhvəyi",
  "Bej",
  "Açıq mavi",
  "Tünd mavi",
  "Tünd yaşıl",
  "Açıq yaşıl",
  "Zeytun",
  "Şabalıdı",
  "Gümüşü",
  "Qızılı",
  "Tünd qırmızı",
  "Bordo",
  "Krem",
  "Fıstıq rəngi",
  "Göyümtül",
  "Şaftalı",
  "Mənzərə yaşılı",
  "Turkuaz",
  "Buz mavisi",
  "Tünd boz",
  "Açıq boz",
  "Parlaq narıncı",
  "Açıq bənövşəyi",
  "Tünd bənövşəyi",
  "Lavanda",
  "Kərpic rəngi",
  "Zəfəran",
  "Neon yaşıl",
  "Neon sarı",
  "Qəhvə",
  "Bordo qırmızı",
  "Xardal",
  "Tünd qızılı",
  "Parlaq yaşıl",
  "Parlaq mavi",
  "Tünd narıncı",
  "Kobalt mavisi",
  "Zümrüd yaşılı",
  "Şərab qırmızı",
  "Metalik",
  "Çoxrəngli",
  "Naxışlı",
  "Zolaqlı",
  "Göy qurşağı",
  "Kollaj rəngli",
  "Kamuflyaj",
  "Mücərrəd",
  "Çiçəkli",
  "Geometrik",
];
